
stages:
- stage: init
  displayName: 'Init Stage'
  jobs:
  - job: prepare_workspace
    displayName: 'Prepare and Init Workspace'
    steps:

    - script: |
        echo -e "\033[0;32mRepository: $(Build.Repository.Name)\033[0m"
        echo -e "\033[0;33mBranch: $(Build.SourceBranchName)\033[0m"
      displayName: 'Print repo and branch'

- stage: Build
  displayName: 'Build Stage'
  jobs:
  - job: Job1
    displayName: 'Job'
    steps:
    - script: |
        echo Step 1
      displayName: 'Step 1'
    - script: |
        echo Step 2
      displayName: 'Step 2'