parameters:
  - name: appFrameworkType
    type: string
    default: "nodejs"

resources:
  repositories:
    - repository: FcpPipelineCommon
      name: DEFRA/fcp-pipeline-common
      endpoint: DEFRA-ADP
      type: github

variables:
  appName: $[replace(variables['Build.Repository.Name'], 'DEFRA/', '')]

stages:
  - stage: Build
    displayName: "Build Stage"
    variables:
      - template: variables.yml

    jobs:
      - job: appVersion
        displayName: "Get App Version"
        steps:
          - script: |
              echo APP_NAME=$(APP_NAME)
            displayName: "Set App Version"
          - template: /ado-pipeline/init/app-version.yaml
            parameters:
              appFrameworkType: ${{ parameters.appFrameworkType }}

      - job: prepare_workspace
        displayName: "Prepare and Init Workspace"
        steps:
          - script: |
              echo -e "\033[0;32mRepository: $(Build.Repository.Name)\033[0m"
              echo -e "\033[0;33mBranch: $(Build.SourceBranchName)\033[0m"
            displayName: "Print repo and branch"

      - job: BuildingApplication
        displayName: "Build"
        steps:
          - checkout: self
          - checkout: FcpPipelineCommon
          - template: /ado-pipeline/build/build-${{ parameters.appFrameworkType }}.yaml

  - stage: stage
    displayName: "Stage"
    variables:
      - template: variables.yml
    jobs:
      - job: SnyckScanApplication
        displayName: "Snyk Application Scan"
        steps:
          - checkout: self
          - checkout: FcpPipelineCommon
          - template: /ado-pipeline/stage/snyk-scan-application.yaml
            parameters:
              appFrameworkType: ${{ parameters.appFrameworkType }}
      - job: SonarCloud
        displayName: "SonarCloud Analysis"
        steps:
          - checkout: self
          - checkout: FcpPipelineCommon
          - template: /ado-pipeline/stage/sonar-cloud.yaml
            parameters:
              appFrameworkType: ${{ parameters.appFrameworkType }}
      - job: HelmTemplate
        displayName: "Build Helm Template"
        steps:
          - checkout: self
          - checkout: FcpPipelineCommon
          - template: /ado-pipeline/stage/build-helm.yaml
            parameters:
              appFrameworkType: ${{ parameters.appFrameworkType }}
