
stages:
- stage: init
  displayName: 'Init Stage'
  jobs:
  - job: prepare_workspace
    displayName: 'Prepare Workspace'
    steps:

    - script: |
        echo "This step is not required for this pipeline"
        echo "testing the fake key: AKIAIOSFODNN7EXAMPLE"
      displayName: 'Clean workspace'

    - script: |
        echo "The branch name is: $(Build.SourceBranch)"
      displayName: 'Get default branch'

- stage: Build
  displayName: 'Build Stage'
  jobs:
  - job: Job1
    displayName: 'Job'
    steps:
    - script: |
        echo Step 1
      displayName: 'Step 1'
    - script: |
        echo Step 2
      displayName: 'Step 2'
