schedules:
  - cron: "0 0 * * 0" # every Sunday at midnight
    displayName: Weekly Sunday Midnight
    branches:
        include:
        - main

variables:
  - group: fcp-pipeline-common-variables
  - group: fcp-pipeline-common-secrets
  - group: fcp-pipeline-snd2-variables

resources:
  repositories:
    - repository: FcpPipelineCommon
      name: defra/fcp-pipeline-common
      endpoint: DEFRA-ADP
      type: github
      # ref: refs/heads/branch-name
stages:
  - stage: BetaDestroy
    pool:
      name: DEFRA-FFC-SND2-ubuntu2204
    displayName: Destroy Beta Deployment Resources

    jobs:
      - job: Decommissioning
        displayName: Decommissioning
        condition: succeeded()
        steps:
          - checkout: self
          - checkout: FcpPipelineCommon
          - template: /ado-pipeline/decommission/discovery-and-destroy.yaml
            parameters:
              subscription: $(subscriptionPreFix)-SND2
